language: python
dist: bionic
sudo: true
services:
  - postgresql
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install tox tox-travis
script:
  - tox
env:
  global:
    PGDATABASE: django_generic_filters
    PGHOST: localhost
    PGUSER: postgres


stages:
  - lint
  - test

jobs:
  include:
    - { stage: lint, env: TOXENV=flake8, python: 3.8 }
